dist: trusty

language: node_js
node_js:
  - 9

addons:
  - sonarcloud:
      organization: "mrmanolodg"
      token:
        secure: $SONARCLOUD_API_KEY

script: 
  - npm test
  - sonar-scanner

deploy:
  provider: heroku
  api_key:
    secure: 
      api_key: $HEROKU_API_KEY
      app: $HEROKU_APP_NAME