sudo: required
language: node_js
node_js:
  - 9

addons:
  - sonarcloud:
      organization: "mrmanolodg"
      token:
        secure: $SONARCLOUD_API_KEY

services:
  - docker
  - mongodb

before_install:
  - wget -qO- https

install:
  - npm install

script: 
  - npm test
  - sonar-scanner


deploy:
  skip_cleanup: true
  provider : script
    heroku container:login
    heroku container:push web -a $HEROKU_APP_NAME
    heroku container:release web -a $HEROKU_APP_NAME

branch: master