sudo: required
language: node_js
node_js:
  - 9

addons:
  - sonarcloud:
      organization: "mrmanolodg"
      token:
        secure: $SONARCLOUD_API_KEY

services:
  - docker
  - mongodb

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

install:
  - npm install

before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script: 
  - npm test
  - docker build -t fis-ms-movies .
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi' # sonar only on non-PRs

deploy:
  provider : script
  cleanup: false
  script:
    heroku container:login;
    heroku container:push web -a fis-ms-movies;
    heroku container:release web -a fis-ms-movies;
  on:
    branch: master